//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibertyApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://boosty.to/the2pizza/.
        /// </summary>
        public static string Boosty {
            get {
                return ResourceManager.GetString("Boosty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bc1qe76609xu8qay4wt7tnvrxhx4spnjrywwh2jwf3.
        /// </summary>
        public static string BTC {
            get {
                return ResourceManager.GetString("BTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuckRKN1.
        /// </summary>
        public static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE21CD0360000028302649.
        /// </summary>
        public static string Credo {
            get {
                return ResourceManager.GetString("Credo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xE92d1695483bd9E82A1AeEEa02E60797B055c53C.
        /// </summary>
        public static string ETH {
            get {
                return ResourceManager.GetString("ETH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/nezavisimost/FuckRKN1.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Resources/vpnclient.p12.
        /// </summary>
        public static string KeysFilePath {
            get {
                return ResourceManager.GetString("KeysFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2e1a065b84f27e3e8b7c9cd64200b7cf00ccd7b624da5996aba1185408ba5b5b.
        /// </summary>
        public static string NEAR {
            get {
                return ResourceManager.GetString("NEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.patreon.com/2pizza.
        /// </summary>
        public static string Patreon {
            get {
                return ResourceManager.GetString("Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt.fuckrkn1.xyz.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://t.me/FuckRKN1.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C9B7138CE341035BDD191AE748EF7D1DF1D6D408.
        /// </summary>
        public static string ThumbPrintIkeV2VpnCa {
            get {
                return ResourceManager.GetString("ThumbPrintIkeV2VpnCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 480DE86802E8F8A9DE4EC05EF5B34F43D39F7137.
        /// </summary>
        public static string ThumbPrintVpnClient {
            get {
                return ResourceManager.GetString("ThumbPrintVpnClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/FuckRKN1.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xE92d1695483bd9E82A1AeEEa02E60797B055c53C.
        /// </summary>
        public static string USDT {
            get {
                return ResourceManager.GetString("USDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fuckrkn1.org/.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
