//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyApp.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibertyApp.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are for freedom of speech and against any kind of censorship. We are making a non-commercial VPN that does not collect any data..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free VPN 
        ///for free humans.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today, freedom of speech is especially vulnerable. Independent media are banned, people are brainwashed with propaganda, VPN services are blocked, and it is dangerous to express one&apos;s position and opinion. This is the reason why we took on this project. It is non-commercial, no profit is pursued either. We are rather small, but yet, we have a great potential..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App minimized into tray.
        /// </summary>
        public static string AppInTrayNotify {
            get {
                return ResourceManager.GetString("AppInTrayNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be closed..
        /// </summary>
        public static string ApplicationWillBeClosed {
            get {
                return ResourceManager.GetString("ApplicationWillBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuckRKN1.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect at launch.
        /// </summary>
        public static string ConnectAtLaunch {
            get {
                return ResourceManager.GetString("ConnectAtLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting….
        /// </summary>
        public static string ConnectingText {
            get {
                return ResourceManager.GetString("ConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string ConnectionErrorCaption {
            get {
                return ResourceManager.GetString("ConnectionErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string ConnectionHeader {
            get {
                return ResourceManager.GetString("ConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionMenu {
            get {
                return ResourceManager.GetString("ConnectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectText {
            get {
                return ResourceManager.GetString("ConnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        public static string CopyToClipboardCaption {
            get {
                return ResourceManager.GetString("CopyToClipboardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} credits copied to clipboard:
        ///{1}.
        /// </summary>
        public static string CopyToClipboardMessage {
            get {
                return ResourceManager.GetString("CopyToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboardToolTip {
            get {
                return ResourceManager.GetString("CopyToClipboardToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting….
        /// </summary>
        public static string DisconnectingText {
            get {
                return ResourceManager.GetString("DisconnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DisconnectText {
            get {
                return ResourceManager.GetString("DisconnectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are OpenSource. You can support us.
        /// </summary>
        public static string DonateHeader {
            get {
                return ResourceManager.GetString("DonateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us.
        /// </summary>
        public static string DonateMenu {
            get {
                return ResourceManager.GetString("DonateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can support us with donations or any other contribution to improve the service. Pulling requests and creating issues also helps us a lot..
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with encryption keys not found..
        /// </summary>
        public static string EncryptionKeysFileNotFound {
            get {
                return ResourceManager.GetString("EncryptionKeysFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Ecryption Keys Error.
        /// </summary>
        public static string ErrorImportEcryptionKeys {
            get {
                return ResourceManager.GetString("ErrorImportEcryptionKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        public static string ExitApplicationCaption {
            get {
                return ResourceManager.GetString("ExitApplicationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the application will close the connection. Do you want to close connection and exit?.
        /// </summary>
        public static string ExitApplicationMessage {
            get {
                return ResourceManager.GetString("ExitApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions on GitHub.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to VPN on the application launch?.
        /// </summary>
        public static string LaunchConnectExplicit {
            get {
                return ResourceManager.GetString("LaunchConnectExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will connect to the VPN on launch.
        /// </summary>
        public static string LaunchConnectMessage {
            get {
                return ResourceManager.GetString("LaunchConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will minimize into tray on launch.
        /// </summary>
        public static string LaunchHiddenMessage {
            get {
                return ResourceManager.GetString("LaunchHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch with Windows.
        /// </summary>
        public static string LaunchWithWindows {
            get {
                return ResourceManager.GetString("LaunchWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run application on Windows startup?.
        /// </summary>
        public static string LaunchWithWindowsExplicit {
            get {
                return ResourceManager.GetString("LaunchWithWindowsExplicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will start with Windows.
        /// </summary>
        public static string LaunchWithWindowsMessage {
            get {
                return ResourceManager.GetString("LaunchWithWindowsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbps.
        /// </summary>
        public static string Mbps {
            get {
                return ResourceManager.GetString("Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need for encryption keys.
        /// </summary>
        public static string NeedForEncryptionKeys {
            get {
                return ResourceManager.GetString("NeedForEncryptionKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to install encryption keys on the first launch. Encryption keys are required to establish a connection with the VPN server.
        ///
        ///Do you agree to install encryption keys in your system&apos;s storage?
        ///
        ///If you click «No», the application will be closed..
        /// </summary>
        public static string NeedForEncryptionKeysMessage {
            get {
                return ResourceManager.GetString("NeedForEncryptionKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string OpenInBrowserTooltip {
            get {
                return ResourceManager.GetString("OpenInBrowserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run minimized into tray.
        /// </summary>
        public static string RunMinimizedIntoTray {
            get {
                return ResourceManager.GetString("RunMinimizedIntoTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide.
        /// </summary>
        public static string ShowHide {
            get {
                return ResourceManager.GetString("ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Freedom.
        /// </summary>
        public static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Freedom.
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string StatusDisconnected {
            get {
                return ResourceManager.GetString("StatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
